name: Test Leapwork Action
on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Run Leapwork Automated Test flows, schedule Daily regression
        shell: pwsh
        run: |
          # Define headers
          $headers = @{
            "AccessKey" = "te4gnB7n2mTJRxsd"
            "ngrok-skip-browser-warning" = "69488"
          }

          # Define API URL for starting schedule
          $runScheduleId = "7fc95621-572e-4da3-9d7b-d98efdd98cc4"
          $url = "https://b608-139-5-242-71.ngrok-free.app/api/v4/schedules/$runScheduleId/runNow"

          try {
              # Make PUT request to start schedule
              $response = Invoke-RestMethod -Uri $url -Method PUT -Headers $headers -ContentType "application/json" -ErrorAction Stop
              Write-Output "Response: $($response | ConvertTo-Json -Depth 10)"
              Write-Output "Response Status Code: $response.StatusCode"

              # Check if starting schedule was successful
              if ('true') 
              {
                  $jsonResponse = $response | ConvertTo-Json -Depth 10
                  Write-Output "JSON Response: $jsonResponse"
                  
                  $runId = $response.runId
                  Write-Output "runId: $runId"

                  # Store runId in an environment variable for subsequent steps
                  echo "run_id=$runId" >> $env:GITHUB_ENV

                  # Initialize variables
                  $timeDelay = 60  # Delay in seconds
                  $isStillRunning = $true
                  $runItemsId = @()
                  $passedCount = 0
                  $failedCount = 0
                  $resultStatus = 1  # Assume all tests pass initially
                  $testResults = @()  # Array to store test results

                  do {
                      # Simulate waiting
                      Write-Output "Waiting for $timeDelay seconds..."
                      Start-Sleep -Seconds $timeDelay

                      # Make API call to retrieve executedRunItems
                      $runItemsResponse = Invoke-RestMethod -Uri "https://b608-139-5-242-71.ngrok-free.app/api/v4/run/$runId/runItemIds" -Method Get -Headers $headers -ContentType "application/json"
                      Write-Output "ExecutedRunItems: $($runItemsResponse | ConvertTo-Json -Depth 10)"
                      # Filter out already processed runItems
                      $executedRunItems = $executedRunItems | Where-Object { $_ -notin $runItemsId }
                      Write-Output "NewExecutedRunItems: $executedRunItems"
                      foreach ($runItemId in $executedRunItems) {
                          Write-Output "RunItemId: $runItemId"
                          # Make API call to get runItem details
                          $runItem = Invoke-RestMethod -Uri "https://b608-139-5-242-71.ngrok-free.app/api/v4/runItems/$runItemId" -Method Get -Headers $headers -ContentType "application/json"

                          $status = $runItem.Status
                          $testName = $runItem.Name
                          Write-Output "Status: $status, Test Name: $testName"

                          $testResults += [pscustomobject]@{
                              TestName = $testName
                              Status   = $status
                          }

                          switch ($runItem.Status) {
                              "Passed" {
                                  Write-Output "Status of runItem $($runItem.Status): Passed"
                                  $passedCount++
                              }
                              "Failed" {
                                  Write-Output "Status of runItem ${runItemId}: $($runItem.Status)"
                                  $failedCount++
                                  $resultStatus = 0  # Set resultStatus to 0 if any test fails
                              }
                              default {
                                  Write-Output "Unhandled status: $($runItem.Status)"
                              }
                          }

                          # Add runItemId to processed list
                          $runItemsId += $runItemId
                      }

                      # Check if the runStatus is Finished
                      $runStatus = Invoke-RestMethod -Uri "https://b608-139-5-242-71.ngrok-free.app/api/v4/runStatus/$runId" -Method Get -Headers $headers -ContentType "application/json"

                      if ($runStatus -eq "Finished") {
                          # Check if all runItems have been processed
                          $allExecutedRunItems = Invoke-RestMethod -Uri "https://b608-139-5-242-71.ngrok-free.app/api/v4/runRunItems/$runId" -Method Get -Headers $headers -ContentType "application/json"
                          if ($allExecutedRunItems.Count -gt 0 -and $allExecutedRunItems.Count -le $runItemsId.Count) {
                              $isStillRunning = $false
                          }
                      }

                      if ($isStillRunning) {
                          Write-Output "The schedule status is already '$runStatus' - wait a minute..."
                      }

                  } while ($isStillRunning)

                  Write-Output "Passed Count: $passedCount"
                  Write-Output "Failed Count: $failedCount"
                  Write-Output "Result Status: $resultStatus"

                  # Output test results to the pipeline logs
                  foreach ($result in $testResults) {
                      Write-Output "Test Name: $($result.TestName), Status: $($result.Status)"
                  }

                  # Save results to a file
                  $resultFilePath = "test_results.json"
                  $testResults | ConvertTo-Json -Depth 10 | Out-File -FilePath $resultFilePath
                  Write-Output "Test results saved to $resultFilePath"

                  # Upload the result file as an artifact
                  Write-Output "Uploading test results as an artifact..."
                  echo "::set-output name=result_status::$resultStatus"
                  echo "result_status=$resultStatus" >> $env:GITHUB_ENV
                  echo "result_file=$resultFilePath" >> $env:GITHUB_ENV

              } else {
                  Write-Error "Failed to start schedule. HTTP status code: $($response.StatusCode)"
                  exit 1
              }

          } catch {
              Write-Error "Error occurred: $_"
              exit 1
          }
      - name: Upload test results artifact
        uses: actions/upload-artifact@v2
        with:
          name: test_results
          path: test_results.json
