name: Display Run Items Property

on:
  push:
    branches:
      - main

jobs:
  display_property:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      # Step 2: Call RunNow API to get runId
      - name: Get RunId
        id: get_run_id
        run: |
          # Replace with your actual API call logic using curl or another HTTP client
          # Example: Call RunNow API and capture runId from response
          run_id=$(curl -s -X PUT -H "Authorization: Bearer $ACCESS_TOKEN" "https://fba4-202-173-125-59.ngrok-free.app/api/v4/schedules/7fc95621-572e-4da3-9d7b-d98efdd98cc4/runNow")
          echo "::set-output name=run_id::$run_id"

      # Step 3: Call RunItemIds API with obtained runId to get runItemIds
      - name: Get RunItemIds
        id: get_run_item_ids
        run: |
          run_id=${{ steps.get_run_id.outputs.run_id }}
          # Replace with your actual API call logic
          run_item_ids=$(curl -s -X GET -H "Authorization: Bearer $ACCESS_TOKEN" "https://fba4-202-173-125-59.ngrok-free.app/api/v4/run/$run_id/runItemIds" | jq -r '.runItemIds | .[]')
          echo "::set-output name=run_item_ids::$run_item_ids"

      # Step 4: Iterate over runItemIds and call RunItems API for each, displaying required property
      - name: Display Property from RunItems
        id: display_property
        run: |
          run_item_ids=${{ steps.get_run_item_ids.outputs.run_item_ids }}
          for run_item_id in $run_item_ids; do
            # Replace with your actual API call logic for RunItems API
            property_value=$(curl -s -X GET -H "Authorization: Bearer $ACCESS_TOKEN" "https://fba4-202-173-125-59.ngrok-free.app/api/v4/runItems/$run_item_id" | jq -r '.property')
            echo "Property value for runItemId $run_item_id: $property_value"
          done
