name: Test Leapwork Action

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:  # Allows manual triggering from Actions tab

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Run Leapwork Automated Test flows, schedule Daily regression
        shell: pwsh
        run: |
          $headers = @{}
          $headers.Add("AccessKey", "ASvAPneQYwUL1VTX")
          $runScheduleId = "7fc95621-572e-4da3-9d7b-d98efdd98cc4"
          $runNow = Invoke-WebRequest -Method PUT -ContentType "application/json" -Headers $headers "http://vmctrl01.westeurope.cloudapp.azure.com:9001/api/v3/schedules/$runScheduleId/runNow?TEST_VALUE='ABC'"
          Write-Host "Result: $($runNow)"
          if ($runNow.StatusCode -ne 200) { throw "Could not run schedule." }
          $runNowResponse = $runNow.Content | ConvertFrom-Json
          $runId = $runNowResponse.RunId

          # Poll for run results
          do {
            Start-Sleep -Seconds 5
            Write-Host "Polling for run results. Runid= $($runId)"
            $runResult = Invoke-WebRequest -ContentType "application/json" -Headers $headers "http://vmctrl01.westeurope.cloudapp.azure.com:9001/api/v3/run/$runId" | ConvertFrom-Json
          } while ($runResult.Status -ne 'Finished')

          Write-Host "Results received."
          Write-Host "Run Result: $($runResult)"
