name: Test Leapwork Action

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      
      - name: Run Leapwork Automated Test flows, schedule Daily regression
        shell: pwsh
        run: |
          $headers = @{
            "AccessKey" = "ASvAPneQYwUL1VTX"
            "ngrok-skip-browser-warning" = "69420"
          }
          $runScheduleId = "d41f169d-88d5-442e-b8ba-9afe9dc01c3a"
          $url = ""https://fba4-202-173-125-59.ngrok-free.app/api/v4/schedules/7fc95621-572e-4da3-9d7b-d98efdd98cc4/runNow"
          $response = Invoke-WebRequest -Uri $url -Method PUT -Headers $headers -ContentType "application/json"

          if ($response.StatusCode -ge 200 -and $response.StatusCode -lt 300) {
              $jsonResponse = $response.Content | ConvertFrom-Json
              $runId = $jsonResponse.runId
              Write-Output "runId: $runId"

              # Store runId in an environment variable for subsequent steps
              echo "run_id=$runId" >> $GITHUB_ENV

              # Use runId in the next API call
              $url2 = "https://fba4-202-173-125-59.ngrok-free.app/api/v4/run/$runId/runItemIds"
              $response2 = Invoke-WebRequest -Uri $url2 -Method GET -Headers $headers -ContentType "application/json"

              if ($response2.StatusCode -ge 200 -and $response2.StatusCode -lt 300) {
                  $jsonResponse2 = $response2.Content | ConvertFrom-Json
                  $runItemId = $jsonResponse2.RunItemIds[0]
                  Write-Output "runItemId: $runItemId"
          
                  # Save runItemId to an environment variable for subsequent use
                  echo "run_item_id=$runItemId" >> $GITHUB_ENV
              } else {
                  Write-Error "Failed to retrieve runItemId. HTTP status code: $($response2.StatusCode)"
                  exit 1
              }
          } else {
              Write-Error "Failed to retrieve runId. HTTP status code: $($response.StatusCode)"
              exit 1
          }
