name: Test Leapwork Action
on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      
      - name: Run Leapwork Automated Test flows, schedule Daily regression
        shell: pwsh
        run: |
          # Define headers
          $headers = @{
            "AccessKey" = "Qa56IlDnepCscGjY"
            "ngrok-skip-browser-warning" = "69488"
          }
          
          # Define API URL for starting schedule
          $runScheduleId = "1b5c204b-37dc-47f1-b24b-84588728b56d"
          $url = "https://e64e-49-36-183-249.ngrok-free.app/api/v4/schedules/$runScheduleId/runNow"
          
          try {
              # Make PUT request to start schedule
              $response = Invoke-RestMethod -Uri $url -Method PUT -Headers $headers -ContentType "application/json" -ErrorAction Stop
              Write-Output "Response: $($response | ConvertTo-Json -Depth 10)"
              Write-Output "Response Status Code: $($response.StatusCode)"
              # Check if starting schedule was successful
              if ('true') {
                  $jsonResponse = $response | ConvertTo-Json -Depth 10
                  Write-Output "JSON Response: $jsonResponse"
                  
                  $runId = $response.RunId
                  Write-Output "runId: $runId"

                  # Store runId in an environment variable for subsequent steps
                  echo "run_id=$runId" >> $env:GITHUB_ENV

                  # Initialize variables
                  $timeDelay = 60  # Delay in seconds
                  $isStillRunning = $true
                  $runItemsId = @()
                  $passedCount = 0
                  $failedCount = 0

                  do {
                      # Simulate waiting
                      Write-Output "Waiting for $timeDelay seconds..."
                      Start-Sleep -Seconds $timeDelay

                      # Make API call to retrieve executedRunItems
                      $executedRunItems = Invoke-RestMethod -Uri "https://e64e-49-36-183-249.ngrok-free.app/api/v4/run/$runId/runItemIds" -Method Get -Headers $headers -ContentType "application/json"
                      Write-Output "ExecutedRunItems: $($executedRunItems | ConvertTo-Json -Depth 10)"
                      # Filter out already processed runItems
                      $executedRunItems.RunItemIds = [string[]]$executedRunItems.RunItemIds
                      $newExecutedRunItems = $executedRunItems.RunItemIds | Where-Object { $_ -notin $runItemsId }
                      Write-Output "NewExecutedRunItems: $($newExecutedRunItems | ConvertTo-Json -Depth 10)"
                      foreach ($runItemId in $newExecutedRunItems) {
                          Write-Output "RunItemId: $runItemId"
                          # Make API call to get runItem details
                          $runItem = Invoke-RestMethod -Uri "https://e64e-49-36-183-249.ngrok-free.app/api/v4/runItems/$runItemId" -Method Get -Headers $headers -ContentType "application/json"

                          $status = $runItem.Status
                          Write-Output "Status: $status"

                          switch ($runItem.Status) {
                              "Passed" {
                                  Write-Output "Status of runItem $($runItem.Status): Passed"
                                  $passedCount++
                              }
                              "Failed" {
                                  Write-Output "Status of runItem ${runItemId}: $($runItem.Status)"
                                  $failedCount++
                              }
                              default {
                                  Write-Output "Unhandled status: $($runItem.Status)"
                              }
                          }

                          # Add runItemId to processed list
                          $runItemsId += $runItemId
                      }

                      # Check if the runStatus is Finished
                      Write-Output "RunId for RunStatus  : $runId"
                      $runStatus = Invoke-RestMethod -Uri "https://e64e-49-36-183-249.ngrok-free.app/api/v4/run/$runId/status" -Method Get -Headers $headers -ContentType "application/json"
                      Write-Output "Run Status : $runStatus"
                      if ($runStatus -eq "Finished") {
                          # Check if all runItems have been processed
                          $allExecutedRunItems = Invoke-RestMethod -Uri "https://e64e-49-36-183-249.ngrok-free.app/api/v4/runRunItems/$runId" -Method Get -Headers $headers -ContentType "application/json"
                          if ($allExecutedRunItems.Count -gt 0 -and $allExecutedRunItems.Count -le $runItemsId.Count) {
                              $isStillRunning = $false
                          }
                      }

                      if ($isStillRunning) {
                          Write-Output "The schedule status is already '$runStatus' - wait a minute..."
                      }

                  } while ($isStillRunning)

                  Write-Output "Passed Count: $passedCount"
                  Write-Output "Failed Count: $failedCount"
                  
                  # Here you can add logic to send an email with results or any other follow-up actions.

              } else {
                  Write-Error "Failed to start schedule. HTTP status code: $($response.StatusCode)"
                  exit 1
              }

          } catch {
              Write-Error "Error occurred: $_"
              exit 1
          }
